### ISSUE TITLE
Can't break lines (enter key) on 1.6.0

### ISSUE THREAD

**Issue by akibasocial** [chucker/Mastonaut#103]
> First of all, I'M SORRY
> I was the one who asked for a new release because 1.5.0 was a bit old 😭 

Since the update to `1.6.0` the editor doesn't allow to break lines with `enter` key

It simply ignores it and put everything on a single continuous line of text

Anything else works fine

**Comment by chucker** [comment]
Will be fixed in 1.6.1.

Workarounds for 1.6.0:

* you can hit <kbd>opt</kbd>-<kbd>return</kbd> instead.
* you can start searching for some random hashtag (e.g., type `#ex`) or username, then delete that again. Then <kbd>return</kbd> will work.
