### ISSUE TITLE
Feature Request: Make Search more discoverable 

### ISSUE THREAD

**Issue by aptonline** [chucker/Mastonaut#12]
First of all, thanks for forking Mastonaut and making a new binary available, it's good to see the app live on especially now more users are making the jump to Mastodon 👍🏼.

One major omittance from Mastonaut is the ability to search for people and posts.  Is this something you are looking to implement in the future?

Happy to support the project if I can.

Many thanks

**Comment by chucker** [comment]
Hey,

Thanks for your interest! There is in fact a search feature, although it isn't that obvious. You can hit ⌘-⇧-F or go to Window → Search…

(It also seems to be a bit flaky…)

**Comment by aptonline** [comment]
That’s for the heads up, certainly not very discoverable but they’re not the less.

looking forward to future updates 😀

**Comment by chucker** [comment]
(Note to self: consider adding to default toolbar)
