### ISSUE TITLE
Option to show entire content in the main window

### ISSUE THREAD

**Issue by clauseggers** [chucker/Mastonaut#138]
I would love it if you could make it an option to simply show the entire toot content in the main window.
<img width="742" alt="Screenshot 2023-06-18 at 16 06 51" src="https://github.com/chucker/Mastonaut/assets/868987/1621330a-ee2e-4deb-8630-4541b10953cf">

As it stands now it is a constant annoyance to have to click i see the whole toot, and if I then do click to see the rest, another very narrow column is opened to the right which I then need several mouse drags to get to a readable width.

These extra columns have never worked and should probably be removed in favour of some other system.

<img width="1072" alt="Screenshot 2023-06-18 at 16 06 44" src="https://github.com/chucker/Mastonaut/assets/868987/9c32bb6f-4683-4835-8f4a-16a8f1178985">

**Comment by chucker** [comment]
(Related: someone once requested an option to not vertically crop thumbnails.)

**Comment by clauseggers** [comment]
Yeah, that too seems like an obvious improvement. There are a lot of unfortunate consequences of this column layout.

**Comment by chucker** [comment]
Please try the following preference in 1.8.0:

<img width="532" alt="image" src="https://github.com/chucker/Mastonaut/assets/20194/d4cd4624-d16b-4e2f-b872-09ae9d720521">

…and set it to 'Never'.

**Comment by clauseggers** [comment]
So far looking great!
