### ISSUE TITLE
Image resources in CoreTootin don't seem to work

### ISSUE THREAD

**Issue by chucker** [chucker/Mastonaut#14]
(This smells like an SDK change, but surely that's not it? But then why did it apparently work before?)

This currently fails:

```swift
public extension NSImage
{
	enum CoreTootin
	{
		public static var globe: NSImage
		{
			return Bundle(for: Persistence.self).image(forResource: "globe")!
		}
```

That resource is `nil`, even though the bundle is (correctly) CoreTootin's bundle (_not_ the main bundle), and CoreTootin's asset catalog _does_ contain that image. This also looks good:

    xcrun assetutil --info long/path/to/CoreTootin.framework/Resources/Assets.car

But, indeed, it seems to open the wrong assets catalog:

```swift
		let bundle1 = Bundle.main
		let resource1 = bundle1.image(forResource: "favorited")

		let bundle2 = Bundle(for: Persistence.self) // this is the different bundle
		let resource2 = bundle2.image(forResource: "favorited") // this should be `nil` but isn't
```

**Comment by uliwitness** [comment]
If this is SwiftPM and CoreTootin is a Swift package, you need to use `Bundle.module`. SwiftPM dependencies don't get a real bundle, they get statically linked into the app (meaning `Bundle(for: SomeCoreTootinClass.self)` always gives the app in which the code resides), and their resources are just a subfolder. SwiftPM synthesizes `Bundle.module` to let you get at resources in that folder.

**Comment by chucker** [comment]
(The real issue is that, for whatever reason, `CoreTootin` is built as a framework but not actually used that way; instead, its Swift code just gets added to Mastonaut directly.

This may be a regression I introduced at some point?)
