### ISSUE TITLE
Crash on Reply

### ISSUE THREAD

**Issue by sweetmslily** [chucker/Mastonaut#147]
Hi there. Mastodon client 1.7.0 downloaded from the GitHub link, running on an M2 Air with macOS Sonoma 14.0 Beta. 

Client fires up correctly but crashes when I click the reply button on anyone's toots. Also crashed when I tried to edit/remove accounts from the Account Settings dialogue. I realize this is likely to do with the macOS Beta, but thought you should be aware of the issue to see if something on your side needs changing to work with the new macOS release. 

Attached the macOS crash report as a text file. Let me know if there's anything else that would help. 

[Mastonaut Crash Log 23.07.19.odt](https://github.com/chucker/Mastonaut/files/12100961/Mastonaut.Crash.Log.23.07.19.odt)

**Comment by chucker** [comment]
Thanks for reporting, but someone else was faster. :)

>I realize this is likely to do with the macOS Beta

[It is](https://github.com/chucker/Mastonaut/issues/144), and it'll be fixed in the next release.

**Comment by sweetmslily** [comment]
Awesome! Glad you’re on top of it. 🧡 Thanks for letting me know. I can use the web interface for now until the fix is ready. Appreciate it. Take care, Lily LerouxShe/HerOn Jul 22, 2023, at 3:13 AM, Sören Nils Kuklau ***@***.***> wrote:﻿
Thanks for reporting, but someone else was faster. :)

I realize this is likely to do with the macOS Beta

It is, and it'll be fixed in the next release.

**Comment by chucker** [comment]
Fixed in 1.8: https://github.com/chucker/Mastonaut/releases/tag/app-1.8.0

**Comment by sweetmslily** [comment]
Can confirm app is now working with no issues on my end, macOS Sonoma Beta 2 on an M2 Air. Thanks so much! Will let you know if anything resurfaces as the next betas roll in.
