### ISSUE TITLE
Clicking on URL uses only part of URL

### ISSUE THREAD

**Issue by clauseggers** [chucker/Mastonaut#169]
When I click on the link in this toot `https://typo.social/@clauseggers/111353816491039602` I am sent to `https://forum.support.xerox.com/t5/Printing/Are-the-1200-2400-DPI-physical-specs-for-the-VersaLink-C7000/td-p/223882`. This is not the full URL. The full URL in the toot is `https://forum.support.xerox.com/t5/Printing/Are-the-1200-2400-DPI-physical-specs-for-the-VersaLink-C7000/m-p/223894/highlight/true#M18964`

What should happen? Mastonaut should use the full URL.

**Comment by chucker** [comment]
I think the `td-p` thing is actually something that happens on the server end (maybe due to the canonical URL).

But, you're right that the anchor is getting cut off. [That was a bug in 1.8](https://github.com/chucker/Mastonaut/issues/163), and should be fixed in the next release.

**Comment by chucker** [comment]
Should be fixed in 1.9.

**Comment by splorp** [comment]
And chance of back porting this fix to the [1.7.0 High Sierra Edition](https://github.com/chucker/Mastonaut/releases/tag/app-1.7.0-hse)?

**Comment by chucker** [comment]
> And chance of back porting this fix to the [1.7.0 High Sierra Edition](https://github.com/chucker/Mastonaut/releases/tag/app-1.7.0-hse)?

Probably. I'll try to get to it.
