### ISSUE TITLE
Test not passing: ImageResizeTests.testResizeGrayscaleImage

### ISSUE THREAD

**Issue by sbeitzel** [chucker/Mastonaut#30]
It seems that `vImageBuffer_InitWithCGImage` comes back with some error code when we pass in the grayscale image. Currently, this crashes since we're dereferencing a null pointer.

**Comment by chucker** [comment]
Looks like it has been broken since at least `d856953b1afd66e3bf31fb8264971e3c00aaa05e`, the first public commit.
