### ISSUE TITLE
Can't paste in 1.4.0

### ISSUE THREAD

**Issue by edwardloveall** [chucker/Mastonaut#43]
I just downloaded 1.4.0 and when I try to paste, it doesn't let me. Here's a demo:

https://user-images.githubusercontent.com/49549/204070450-0e04831a-fa59-4c22-82c3-17b3e934b0c1.mp4

Oddly, `Paste and Match Style` seems to work.

**Comment by sbeitzel** [comment]
Hmm. Probably to do with the type stuff I did in e23bb1a -- I'll take a look.

**Comment by EricGus** [comment]
I can confirm this same issue, no PASTE .. either via keyboard shortcut or MENU/paste ..

**Comment by sbeitzel** [comment]
It looks like paste is seeing the clipboard contents and trying to treat it like an attachment. I should be able to put a fix together fairly quickly. As noted above, paste and match style works around this, but I suspect it is more subtle than just twiddling the acceptable paste types. While debugging the paste, I tried dropping a PNG into the composition window and that didn't work, either. I may wind up reverting the UTType update in the text window classes until I can sort this out for certain.

**Comment by stuffmc** [comment]
Paste and Match Style doesn't work when copying a picture previously copied with ⇧ ⌘ 3/4 from the pasteboard :( I hate to be picky on this, but I think for me for now it makes more sense to reinstall 1.3.10

**Comment by chucker** [comment]
> I hate to be picky on this, but I think for me for now it makes more sense to reinstall 1.3.10

Yeah, sorry about this regression.
