### ISSUE TITLE
Feature Request - Edit Post support

### ISSUE THREAD

**Issue by chrisale** [chucker/Mastonaut#45]
I'm sure this is already on your mind.

**Comment by chucker** [comment]
It is, but I haven't looked into how easy this is.

**Comment by chucker** [comment]
- [ ] See whether a post has had edits
- [ ] Show previous versions
- [ ] Allow you to edit an existing post of yours

**Comment by chucker** [comment]
Early prototype for showing edits:

<img width="311" alt="image" src="https://user-images.githubusercontent.com/20194/211214255-cba8fcd1-1275-40c4-9fb5-6d42e1c91c4c.png">

**Comment by chucker** [comment]
This is basically done, and should come sometime in Feb.

**Comment by chucker** [comment]
Really stretching the definition of February there, but this now shipped: https://github.com/chucker/Mastonaut/releases/tag/app-1.6.0
