### ISSUE TITLE
Feature Request - View Favourites to Column selector?

### ISSUE THREAD

**Issue by chrisale** [chucker/Mastonaut#47]
I just realized there was a "View Favourites" option in the Account menu. Seems counter-intuitive that it is not available with the local/federated/home/notifications dropdown and/or enabled with a keyboard shortcut to quickly bring it up in the details pane? 

[Edited to solve typo-induced unreadability]

**Comment by stuffmc** [comment]
+1

**Comment by chucker** [comment]
Hmm, I feel like this should really be a fourth section of the lozenge in your profile (currently: Toots, Toots and Replies, Media).

_Bookmarks_, OTOH, should be in the columns popup. (Not that bookmarks are currently implemented. That's #53…)

At least that's how I would personally understand the distinction:

* favorites are something you give someone to tell them you've appreciated their post,
* boosts are a way of letting others know about it,
* bookmarks are sort of a "save for reading later" thing, just like in a web browser

**Comment by chucker** [comment]
Alrighty… https://github.com/chucker/Mastonaut/pull/60

**Comment by chucker** [comment]
This has now shipped :)
