### ISSUE TITLE
More Keyboard Shortcuts please

### ISSUE THREAD

**Issue by stuffmc** [chucker/Mastonaut#50]
I'm used to have a selected <s>tweet</s> toot :) and hit ⌘ C and it will copy the URL of it. ⇧ ⌘ V could be "Copy Text". Right now, the "Copy" Item in the menu is simply disabled.

Generally the App could be more Keyboard-friendly.

**Comment by chucker** [comment]
Is there precedent for ⌘ ⇧ C (I presume you mean C, not V) being "Copy Text"? Tweetbot for one doesn't seem to have that shortcut.

**Comment by stuffmc** [comment]
Twitterrific?

**Comment by stuffmc** [comment]
> I'm used to have a selected tweet toot :) and hit ⌘ C and it will copy the URL of it. ⇧ ⌘ V could be "Copy Text". Right now, the "Copy" Item in the menu is simply disabled.
> 
> Generally the App could be more Keyboard-friendly.

I mean V, not C ;-) Thanks for the headsup.

**Comment by chucker** [comment]
Fair enough. Haven't used Twitterrific in a long, long time. :)
