### ISSUE TITLE
Feature request: Bookmark support

### ISSUE THREAD

**Issue by BlkPingu** [chucker/Mastonaut#53]
I'm sure you have this on your radar already but just for reference :)|

<img width="287" alt="Screenshot 2022-11-28 at 00 50 36" src="https://user-images.githubusercontent.com/28692167/204166408-ae732938-0c2f-4d99-af0c-39fc819997d8.png">

**Comment by chucker** [comment]
Menu item part is done:

<img width="262" alt="image" src="https://user-images.githubusercontent.com/20194/205457633-0ac5d78e-8412-4a02-9a11-78af8848e756.png">

Viewing one's bookmarks isn't yet (see also #47)

**Comment by chucker** [comment]
This has now shipped :)
