### ISSUE TITLE
1.4 - Paste and Match Style Works - Paste does not

### ISSUE THREAD

**Issue by chrisale** [chucker/Mastonaut#54]
I know it's been noted that 1.4 broke copy/paste functionality but I thought it worth mentioning hopefully from a debugging POV that I just found that "paste and match style" (Command-Option-Shift-V) DOES work. Perhaps this will shed a light.

**Comment by chucker** [comment]
Thanks for the info. I did track down _one_ of the reasons that broke, but I'm not sure I want to risk re-introducing that change yet. (See https://github.com/chucker/Mastonaut/pull/26#issuecomment-1332254872 for nerdy details.)
