### ISSUE TITLE
Feature request: Separate default status for new posts and replies

### ISSUE THREAD

**Issue by sindarina** [chucker/Mastonaut#64]
Currently, there's a single setting for default status privacy. The Toot! mobile app has two separate settings; one for new posts, and one for replies. This allows the user to select 'Public' for anything new they post, while using 'Unlisted' for any follow-up posts in the same thread, or replies to other people's posts. It'd be great if Mastonaut could support something similar?

Have attached a screenshot of how Toot! shows this in the app settings.

![tootapp-default-visibility-settings](https://user-images.githubusercontent.com/6074566/205457284-d0a8b483-1f69-491c-9cd1-0b4c7dbff8b3.png)

**Comment by chucker** [comment]
Coming in Feb:

![image](https://user-images.githubusercontent.com/20194/213605327-2ed4e295-4001-4b9c-95ba-b51cbcd581ad.png)

**Comment by chucker** [comment]
This finally shipped. https://github.com/chucker/Mastonaut/releases/tag/app-1.6.0
