### ISSUE TITLE
Remaining character count doesn't update, sometimes?

### ISSUE THREAD

**Issue by sindarina** [chucker/Mastonaut#67]
When creating a new post, the remaining character count seems to stop updating sometimes, possibly because something has been pasted into it, like a URL? Not entirely sure when this happens or how to reproduce, but I think it might have something to do with the fact that URLs have a fixed 23-character length within Mastodon, and therefore this;

> Type something, paste URL; https://domain.example/followed/by/a/long/string/such/as/a/blog/post/
> 
> Type additional text, but remaining character count no longer updates

basically stops counting after the first semicolon? 🤔

**Comment by chucker** [comment]
Indeed. The URL detection took cases where there was something _before_ the URL into account, but not cases where there was text _after_ it; the entire remainder was ignored.
