### ISSUE TITLE
Fails to correctly authenticate against gotosocial

### ISSUE THREAD

**Issue by nigelm** [chucker/Mastonaut#73]
I have a gotosocial server (version 1.6.0rc1).  Mastonaut fails to authenticate correctly authenticate against it - doing the oauth dance up to the point where my browser (Firefox) attempts to pass the token back to Mastonaut, when I get the following dialog

<img width="263" alt="Screenshot 2022-12-09 at 16 21 33" src="https://user-images.githubusercontent.com/52820/206746858-d8fdd060-2fe8-484b-bfcb-60a74a1d868b.png">

Other Mastodon clients do work correctly.

This also happened with the earlier (original author) 1.3.x releases and 1.4.0 as well as with the current 1.4.1

Should you need it I can provide additional debug info (give me hints how to get better logging/debug info), or an account on my test gotosocial server.

**Comment by chucker** [comment]
>an account on my test gotosocial server.

That would be great. I couldn't find _any_ public gotosocial server in my cursory search. :(

**Comment by nigelm** [comment]
Hi

Could you drop me an email to heavy.lamp1111@fastmail.com (masked temporary address since its in a public issue), and I'll send you account credentials across.

> That would be great. I couldn't find _any_ public gotosocial server in my cursory search. :(

Problem with gotosocial is it tends to be used for *small* instances, and the admin is command line based (so no web based self service account creation).  I'm really only trying it out currently - I may well move to it as a self hosted single user setup - but standard Mastodon clients *should* work with it.

**Comment by chucker** [comment]
Hm, oddly, I'm getting `Login error: mastodonError("invalid_request")`

**Comment by nigelm** [comment]
Since that instance is behind a https proxy I can see the raw data hitting the box, and what appears to be going wrong  is when Mastonaut does `POST /oauth/token` with (reformatted for readability JSON):-

```json
{
  "client_id": "ELIDED CLIENT ID",
  "scope": [
    "read",
    "write",
    "push",
    "follow"
  ],
  "redirect_uri": "mastonaut-auth://oauth/grant/toots.things.muesli.org.uk/code/",
  "code": "ELIDED MAGIC CODE",
  "client_secret": "ELIDED CLIENT SECRET",
  "grant_type": "authorization_code"
}
```
 
and gets this response back with HTTP status 400:-
```json
{
  "error": "invalid_request",
  "error_description": "Bad Request: json: cannot unmarshal array into Go struct field tokenRequestForm.scope of type string"
}
```

In contrast Pinafore sends `POST /oauth/token` with (reformatted for readability JSON):-
```json
{
  "client_id": "ELIDED",
  "client_secret": "ELIDED",
  "redirect_uri": "https://pinafore.social/settings/instances/add",
  "grant_type": "authorization_code",
  "code": "ELIDED"
}
```

So my suspicion is that gotosocial is not expecting the `scope` element and is giving up on that.

A trace with `whalebird` (which does OOB Oauth by giving the user a code to paste into the app), looks like it supports that difference on the `/oauth/token` endpoint.

Hope that leads you in the right direction.  Of course if something else requires the `scope` then this could be a pain.

**Comment by chucker** [comment]
Bingo, thanks.

Looks like this is a regression from https://github.com/chucker/MastodonKit/commit/4270aa7c87c1967fa82365d6197d6493cc77d301#diff-5365f4ba9af19d76b609db907c5a90c477b0fc28910402f18a18508e77573e9a. [The API docs say space-separated string](https://docs.joinmastodon.org/entities/Token/#scope), but that commit changed it to an array.

**Comment by chucker** [comment]
This has now shipped :)
