### ISSUE TITLE
Default status privacy popup initial value not set

### ISSUE THREAD

**Issue by lapcat** [chucker/Mastonaut#74]
Steps to reproduce:

1. Open Preferences
2. Select Composing
3. Select Unlisted in the Default status privacy poup
4. Close Preferences
5. Open Preferences
6. Select Composing

Expected results: Unlisted is selected in the Default status privacy popup.

Actual results: Public is selected in the Default status privacy popup.

**Comment by chucker** [comment]
I revamped the data binding behind that UI in 1.6. Please try again with that version: https://github.com/chucker/Mastonaut/releases/tag/app-1.6.0

**Comment by lapcat** [comment]
Fixed in 1.6.0, thanks!
