### ISSUE TITLE
Notifications are sent for favorites even when disabled in preferences

### ISSUE THREAD

**Issue by lapcat** [chucker/Mastonaut#76]
I've disabled notifications for favorites in Mastonaut Preferences, but I still get notifications for them. There's also a Dock badge for them.

<img width="782" alt="Screen Shot 2022-12-16 at 7 09 53 PM" src="https://user-images.githubusercontent.com/56086/208215528-c1d9e827-dc94-44c3-8a6d-36db934d33ce.png">

**Comment by chucker** [comment]
I was afraid that might happen. Oops.

need to investigate:

* are notification filters stored on the instance? (if so, would make code simpler and also make the setting sync with other apps)
* failing that, need to hook into the notifications pipeline differently

**Comment by chucker** [comment]
Sorry again about this bug. I believe this is fixed in 1.5.0, which is now out.
