### ISSUE TITLE
Filters options not saved

### ISSUE THREAD

**Issue by aboudou** [chucker/Mastonaut#77]
Hello,

With Mastonaut 1.4.1, filters don't work as expected, as some option changes are not saved : 

- "Only apply if the whole…" checkbox status is not saved. If unchecked, the next time the filter windows is open, it's checked again, thus filters on some words only are not applied
- "Action" status is never saved too.

(I didn't tried the other options).

<img width="1747" alt="Capture d’écran 2022-12-22 à 07 37 31" src="https://user-images.githubusercontent.com/2165241/209072931-2b5513b2-b019-4bd8-8999-9fc38f328e41.png">

Thanks :)

**Comment by chucker** [comment]
There's a multitude of issues here.

[First, there are newer, fancier v2 filters that we don't support yet.](https://github.com/chucker/Mastonaut/issues/78) We'll probably have to eventually migrate to those.

But ignoring that for now:

- [ ] When setting an expiration, the filter doesn't seem to get saved at all

I'm seeing no HTTP request at all here.

- [ ] Mastonaut can _read_ `whole_word` (if set elsewhere, e.g. in the web UI), but can't write it

One bug was that it tried to set `wholeWord`. But even changing that to `whole_word`, setting it to false seems to have no effect on the HTTP _response_ I'm getting. The response says `"whole_word": true` no matter what. It appears this is [a Mastodon bug](https://github.com/mastodon/mastodon/issues/21965). The fix doesn't seem to have shipped yet.

- [ ] Mastonaut can't turn `irreversible` _off_ (Action: Hide) once it has been set on

Same Mastodon bug as above.

- [ ] Mastonaut can turn `irreversible` _on_ (Action: Drop Forever), but then doesn't see the result

The response says `"irreversible": true`, as expected, but Mastonaut doesn't seem to set the drop-down correctly.

**Comment by chucker** [comment]
So the TL;DR is: I've fixed a number of bugs on the Mastonaut clientend (pending a release, hopefully in a few weeks), but the two things you point out are actually also broken on the Mastodon API end, as of 4.0.2.

**Comment by aboudou** [comment]
Thanks for your commits.

I'll just have to wait for the next release :)

**Comment by chucker** [comment]
> Thanks for your commits.
> 
> I'll just have to wait for the next release :)

[1.5.0 is now out.](https://github.com/chucker/Mastonaut/releases/tag/app-1.5.0)

Again, some of the bugs are on Masto's end, I'm afraid, but let me know if this already helps a bit!
