### ISSUE TITLE
Feature request: Customize font and font-size of posts in timelines

### ISSUE THREAD

**Issue by kethinov** [chucker/Mastonaut#83]
One big usability benefit would be if there was a way to change the font and font-size of posts with a global setting.

**Comment by chucker** [comment]
Similar vein: https://mastodon.social/@kierankelly/109705738038606563

**Comment by chrisgrieser** [comment]
I'd also very much like to see this. mastonaut seems to have the best UI from all mastodon clients I tried, but the small font size makes it barely usable for me.
