### ISSUE TITLE
High Sierra compat

### ISSUE THREAD

**Issue by chucker** [chucker/Mastonaut#92]
1.4 and newer [require 12.0 Monterey](https://github.com/chucker/Mastonaut/discussions/19), mainly due to my use of SwiftUI. Determine how much effort it is to backport some key features to High Sierra. (For example, editing currently doesn’t use SwiftUI, IIRC.)

Then, consider a release rhythm where every other release (say) has a “High Sierra Edition”.

**Comment by josh64x2** [comment]
@chucker - I was just curious about the benefit you are getting from using SwiftUI?

Thanks!

**Comment by chucker** [comment]
Three things:

* Apple has stated at the past WWDC that SwiftUI is "the future". While that's a broad statement, I think that _does_ mean that they encourage us to use AppKit/UIKit/WatchKit less in the future.
* I do find SwiftUI pleasant to use for simple/common layout scenarios. For example, a LazyVGrid makes it easy to have a preferences layout like in Finder or Safari, where each row has a right-aligned label and a left-aligned control (drop-down, checkbox, etc.) to the right of it, and those in turn are centered. This requires a lot more manual alignment work in AppKit. Something else that's very nice about SwiftUI is the previewed. You can supply one or more pieces of data and basically preview different scenarios: what does the view look like in light mode, dark mode, with one item, with five items, with so many items that it needs to scroll, etc., and keep refreshing those previews as you're making tweaks to the view. This is much trickier to do in AppKit.
* my AppKit knowledge (mid-2000s) predates the existence of AutoLayout/constraints (and also of storyboards). I'm frankly not that well-versed in them and don't find them very handy to use compared to how SwiftUI approaches layout. They're _interesting_ (for example, it's neat that Apple made an ASCII syntax to define them in code), but I get the sense that Apple ultimately realized they're not the right approach.

That said, SwiftUI does still feel a bit like a beta. But I suppose I'm skating to where the puck is going.

**Comment by josh64x2** [comment]
That sounds fair. Hopefully Apple fix SwiftUI's shortcomings one day soon. I'll keep an eye on the project and if I can see something I can help with then I'll let you know.
My skills are mostly AppKit and Objective-C however!

**Comment by chucker** [comment]
Shipped! 🚀 https://github.com/chucker/Mastonaut/releases/tag/app-1.7.0-hse
