### ISSUE TITLE
Notify user of follow requests

### ISSUE THREAD

**Issue by lunasophia** [chucker/Mastonaut#99]
It's possible that I'm just missing it in the UI, but it seems that Mastonaut doesn't display follow requests to the user, and furthermore doesn't provide a way to approve / decline said requests. I have to go to the instance's website to see and interact with them.

**Comment by chucker** [comment]
>It's possible that I'm just missing it in the UI

No, I think that's right; it doesn't seem to be implemented yet.

**Comment by chucker** [comment]
This is ready for 1.8.

**Comment by chucker** [comment]
(1.8 has now shipped)
